name: wif-ci
on:
  push:
    branches:
    - "develop"
jobs:
  build:
    name: "Test WIF"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Printenv
      # print all environment variables
        run: env
        # run: echo ${{ env }}
      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: kubula-420821
          workload_identity_provider: "projects/kubula-420821/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: set crdential_file
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
      - name: List GCP Artifacts
        run: gcloud artifacts repositories list --project=kubula-420821 --location=us-east1