# # .github/workflows/release.yml
# name: goreleaser

# on:
#   pull_request:
#   push:
#     # run only against tags
#     tags:
#       - 'v*.*.*'
#       - '*.*.*-*'

# permissions:
#   contents: write
#   # id-token: write
#   # packages: write
#   # issues: write

# jobs:
#   goreleaser:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Set up Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: stable
#       - name: Get latest Syft version
#         id: latest-version
#         run: |
#           curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
#       - name: Install Cosign
#         uses: sigstore/cosign-installer@main
#       - name: Write Cosign key
#         run: |
#           echo ${secrets.cosign_key} > cosign.key
#       # More assembly might be required: Docker logins, GPG, etc.
#       # It all depends on your needs.
#       - name: Run GoReleaser
#         uses: goreleaser/goreleaser-action@v5
#         with:
#           # either 'goreleaser' (default) or 'goreleaser-pro'
#           distribution: goreleaser
#           # 'latest', 'nightly', or a semver
#           version: "~> v1"
#           args: release --clean
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#           # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
#           # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}